allowBuilds:
  '@parcel/watcher': set this to true or false
  active-win: set this to true or false
  better-sqlite3: set this to true or false
  bufferutil: set this to true or false
  electron: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
  extract-file-icon: set this to true or false
  koffi: set this to true or false
  node-window-manager: set this to true or false
  sharp: set this to true or false
  utf-8-validate: set this to true or false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - active-win
  - better-sqlite3
  - electron
  - esbuild
  - extract-file-icon
  - node-window-manager
  - sharp
  - vue-demi
