import { BrowserWindow } from 'electron'
import type { WindowEvent, WindowInfo } from '../utils/windowWatcher'
import { getWindowWatcher } from '../utils/windowWatcher'
import { getBridgeConnectionController } from '../main'
import { getUserName } from '../database/schema'
import { createScopedLogger } from '../utils/logger'
import { resolveWindowAppIdentity } from './appIdentity'
import { AwarenessPolicyEngine } from './policyEngine'
import {
  loadDesktopAwarenessSettings,
  resetDesktopAwarenessSettings,
  saveDesktopAwarenessSettings,
  toLegacyWatcherConfig,
  validateDesktopAwarenessSettings
} from './settings'
import type {
  DesktopAwarenessSettings,
  DesktopAwarenessSnapshot,
  DesktopContextChangedCallback,
  DesktopContextChangedEvent,
  DesktopContextSnapshot,
  RecentDesktopApp,
  DesktopAwarenessTransitionType
} from './types'

const logger = createScopedLogger('desktop.awareness')
const MAX_RECENT_APPS = 12

function cloneJson<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T
}

function createEmptyContext(): DesktopContextSnapshot {
  return {
    app: null,
    window: null,
    windowTitle: null,
    isFullscreen: false,
    focusedSince: null,
    updatedAt: Date.now()
  }
}

function buildDesktopContextSystemPrompt(
  event: DesktopContextChangedEvent,
  userName: string
): string {
  const lines = [
    '[SYSTEM_EVENT:DESKTOP_CONTEXT_CHANGED]',
    'This signal is automatically generated by the desktop client and is NOT a user-authored message.',
    `user_nickname: ${JSON.stringify(userName)}`,
    `detected_app: ${JSON.stringify(event.app.displayName)}`,
    `app_key: ${JSON.stringify(event.app.canonicalKey)}`,
    `transition_type: ${JSON.stringify(event.transitionType)}`,
    `dwell_ms: ${event.dwellMs}`,
    `confidence: ${JSON.stringify(event.confidence)}`,
    `event_time_utc: ${JSON.stringify(new Date(event.timestamp).toISOString())}`
  ]

  if (event.privacy.titleShared && event.windowTitle) {
    lines.push(`window_title: ${JSON.stringify(event.windowTitle)}`)
  }

  lines.push(
    'guidance:',
    '- Treat this as contextual telemetry, not explicit user intent.',
    '- Do not respond unless the context change is meaningfully useful.',
    '- Do not claim screen details unless capture_screenshot is called.'
  )

  return lines.join('\n')
}

export class DesktopAwarenessService {
  private settings: DesktopAwarenessSettings | null = null
  private current: DesktopContextSnapshot = createEmptyContext()
  private previous: DesktopContextSnapshot | null = null
  private recentApps: RecentDesktopApp[] = []
  private lastEvent: DesktopContextChangedEvent | null = null
  private lastDecision: DesktopAwarenessSnapshot['lastDecision'] = null
  private policy = new AwarenessPolicyEngine()
  private listeners: Set<DesktopContextChangedCallback> = new Set()
  private isRunning = false
  private removeWatcherListener: (() => void) | null = null
  private dwellTimer: NodeJS.Timeout | null = null

  async start(): Promise<void> {
    if (this.isRunning) return

    await this.ensureSettings()
    const watcher = getWindowWatcher()
    const legacyConfig = toLegacyWatcherConfig(this.settings!, await watcher.getConfig())
    await watcher.updateConfig(legacyConfig)

    if (!watcher.isActive()) {
      await watcher.start()
    }

    const activeWindow = watcher.getCurrentWindow()
    if (activeWindow) {
      this.updateContext(activeWindow, 'initial', Date.now(), false)
    }

    this.removeWatcherListener = watcher.onWindowEvent(event => {
      this.handleWindowEvent(event)
    })

    this.isRunning = true
    logger.info('service.started', { settings: this.settings })
  }

  stop(): void {
    if (!this.isRunning) return

    this.removeWatcherListener?.()
    this.removeWatcherListener = null
    this.clearDwellTimer()
    this.isRunning = false
    logger.info('service.stopped')
  }

  isActive(): boolean {
    return this.isRunning
  }

  onContextChanged(callback: DesktopContextChangedCallback): () => void {
    this.listeners.add(callback)
    return () => this.listeners.delete(callback)
  }

  async ingestWindowSnapshot(window: WindowInfo): Promise<void> {
    await this.ensureSettings()
    if (!this.settings?.enabled) return
    this.updateContext(window, 'initial', Date.now(), false)
  }

  async getSettings(): Promise<DesktopAwarenessSettings> {
    await this.ensureSettings()
    return cloneJson(this.settings!)
  }

  async updateSettings(
    patch: Partial<DesktopAwarenessSettings>
  ): Promise<DesktopAwarenessSettings> {
    const current = await this.getSettings()
    this.settings = await saveDesktopAwarenessSettings(
      validateDesktopAwarenessSettings({
        ...current,
        ...patch,
        appScope: {
          ...current.appScope,
          ...(patch.appScope || {})
        },
        privacy: {
          ...current.privacy,
          ...(patch.privacy || {})
        }
      })
    )
    this.policy.reset()
    this.clearDwellTimer()

    if (this.isRunning) {
      const watcher = getWindowWatcher()
      await watcher.updateConfig(toLegacyWatcherConfig(this.settings, await watcher.getConfig()))
      const activeWindow = watcher.getCurrentWindow()
      if (activeWindow) {
        this.updateContext(activeWindow, 'initial', Date.now(), false)
      }
    }

    logger.info('settings.updated', { settings: this.settings })
    this.broadcastSnapshot()
    return cloneJson(this.settings)
  }

  async resetSettings(): Promise<DesktopAwarenessSettings> {
    this.settings = await resetDesktopAwarenessSettings()
    this.policy.reset()
    this.clearDwellTimer()

    if (this.isRunning) {
      const watcher = getWindowWatcher()
      await watcher.updateConfig(toLegacyWatcherConfig(this.settings, await watcher.getConfig()))
    }

    return cloneJson(this.settings)
  }

  getSnapshot(): DesktopAwarenessSnapshot {
    return {
      settings: cloneJson(this.settings || validateDesktopAwarenessSettings(null)),
      current: cloneJson(this.current),
      recentApps: cloneJson(this.recentApps),
      lastEvent: cloneJson(this.lastEvent),
      lastDecision: cloneJson(this.lastDecision)
    }
  }

  private async ensureSettings(): Promise<void> {
    if (!this.settings) {
      this.settings = await loadDesktopAwarenessSettings()
    }
  }

  private handleWindowEvent(event: WindowEvent): void {
    if (!this.settings?.enabled) return

    if (event.type === 'focus') {
      this.updateContext(event.window, 'app-switch', event.timestamp, true)
      return
    }

    if (
      event.type === 'fullscreen' ||
      (event.type === 'maximize' && event.window.isFullscreen) ||
      event.type === 'windowed' ||
      (event.type === 'restore' && !event.window.isFullscreen)
    ) {
      const transitionType: DesktopAwarenessTransitionType = event.window.isFullscreen
        ? 'fullscreen-enter'
        : 'fullscreen-exit'
      this.updateContext(event.window, transitionType, event.timestamp, true)
    }
  }

  private updateContext(
    window: WindowInfo,
    transitionType: DesktopAwarenessTransitionType,
    timestamp: number,
    evaluatePolicy: boolean
  ): void {
    const app = resolveWindowAppIdentity(window)
    const previous = this.current.app ? this.current : null
    const sameApp = previous?.app?.canonicalKey === app.canonicalKey
    const sameWindow = previous?.window?.id === window.id
    const resolvedTransitionType: DesktopAwarenessTransitionType =
      transitionType === 'app-switch' && sameApp && !sameWindow ? 'window-switch' : transitionType

    this.previous = previous
    this.current = {
      app,
      window,
      windowTitle: window.title || null,
      isFullscreen: window.isFullscreen,
      focusedSince: sameWindow ? this.current.focusedSince || timestamp : timestamp,
      updatedAt: timestamp
    }

    this.rememberRecentApp(window)
    this.broadcastSnapshot()

    if (!evaluatePolicy || !this.settings) return
    if (sameWindow && transitionType === 'app-switch') return

    this.clearDwellTimer()
    const minDwellMs = this.policy.getMinDwellMs(this.settings)
    this.dwellTimer = setTimeout(() => {
      this.evaluateAndNotify(resolvedTransitionType)
    }, minDwellMs)
  }

  private evaluateAndNotify(transitionType: DesktopAwarenessTransitionType): void {
    if (!this.settings || !this.current.app || !this.current.focusedSince) return

    const now = Date.now()
    const dwellMs = now - this.current.focusedSince
    const decision = this.policy.evaluate({
      settings: this.settings,
      snapshot: this.current,
      previousSnapshot: this.previous,
      transitionType,
      dwellMs,
      now
    })

    this.lastDecision = {
      ...decision,
      timestamp: now
    }

    if (!decision.shouldNotify) {
      logger.debug('policy.suppressed', this.lastDecision)
      this.broadcastSnapshot()
      return
    }

    const event: DesktopContextChangedEvent = {
      app: this.current.app,
      previousApp: this.previous?.app || null,
      windowTitle: this.settings.privacy.shareWindowTitle ? this.current.windowTitle : null,
      transitionType,
      dwellMs,
      timestamp: now,
      confidence: this.current.app.confidence,
      privacy: {
        titleShared: this.settings.privacy.shareWindowTitle,
        screenshotIncluded: false
      }
    }

    this.lastEvent = event
    this.emitContextChanged(event)
    this.broadcastSnapshot()
  }

  private emitContextChanged(event: DesktopContextChangedEvent): void {
    for (const listener of this.listeners) {
      try {
        listener(event)
      } catch (error) {
        logger.error('listener.failed', error)
      }
    }

    const controller = getBridgeConnectionController()
    if (!controller?.isConnected()) return
    const session = controller.getSession()
    if (!session) return

    const userName = getUserName()?.trim() || 'Desktop User'
    void controller
      .sendMessage({
        content: [
          {
            type: 'text',
            text: buildDesktopContextSystemPrompt(event, userName)
          }
        ],
        metadata: {
          userId: session.userId,
          userName,
          sessionId: session.sessionId,
          messageType: 'notify'
        }
      })
      .catch(error => {
        logger.error('context_notify.failed', error, { app: event.app.canonicalKey })
      })
  }

  private rememberRecentApp(window: WindowInfo): void {
    if (!this.current.app) return
    const existingIndex = this.recentApps.findIndex(
      item => item.app.canonicalKey === this.current.app?.canonicalKey
    )
    if (existingIndex >= 0) {
      this.recentApps.splice(existingIndex, 1)
    }
    this.recentApps.unshift({
      app: this.current.app,
      lastSeenAt: Date.now(),
      windowTitle: window.title || null
    })
    this.recentApps = this.recentApps.slice(0, MAX_RECENT_APPS)
  }

  private broadcastSnapshot(): void {
    const snapshot = this.getSnapshot()
    for (const window of BrowserWindow.getAllWindows()) {
      if (!window.isDestroyed()) {
        window.webContents.send('desktopAwareness:snapshotChanged', snapshot)
      }
    }
  }

  private clearDwellTimer(): void {
    if (this.dwellTimer) {
      clearTimeout(this.dwellTimer)
      this.dwellTimer = null
    }
  }
}

let instance: DesktopAwarenessService | null = null

export function getDesktopAwarenessService(): DesktopAwarenessService {
  if (!instance) {
    instance = new DesktopAwarenessService()
  }
  return instance
}
